### ISSUE TITLE
Attribute called "None" is misinterpreted to be a syntax error

### ISSUE THREAD

**Issue by MarkusMeskanen** [patrys/PythonChecker#11]
If I have a class whose instances have an attribute called `None` (don't ask, not a class I've made) like so:

    class X:
        def __init__(self):
            self.None = True

Python Checker will say "*invalid syntax*" while it's actually proper code, just not recommended.

Same will happen if I access it through an instance:

    x = X()
    print(x.None)

**Comment by patrys** [comment]
Python 2:

```python
>>> class Foo:
...     def __init__(self):
...         self.None = 1
... 
  File "<stdin>", line 3
SyntaxError: cannot assign to None
```

Python 3:

```python
>>> class Foo:
...     def __init__(self):
...         self.None = 1
  File "<stdin>", line 3
    self.None = 1
            ^
SyntaxError: invalid syntax
```

**Comment by MarkusMeskanen** [comment]
Right, silly me.
